In [90]:
#pip install faker 
#pip install pandas

#import the libraries we need
from faker import Faker
import pandas as pd

#create an instance of Faker
fake = Faker(locale='en_PH')

In [91]:
#create a fake name
fake.name()

'Paula Palmer'

In [ ]:
#create random phone numbers
from faker import Faker
from faker.providers.phone_number import Provider

class PhilippinesPhoneNumberProvider(Provider):
    def philippines_phone_number(self):
        return f'+63 {self.msisdn()[3:]}'  # msisdn generates a complete string of numbers, this formats it
    #https://en.wikipedia.org/wiki/List_of_telephone_country_codes

fake = Faker()
fake.add_provider(PhilippinesPhoneNumberProvider)

print(fake.philippines_phone_number())

+63

In [ ]:
#create random account number
import random
import string

def generate_customer_id(length=10):
    #generate random alphanumeric string of given length
    #letters_and_digits = string.ascii_uppercase + string.digits
    letters_and_digits =  string.digits
    return ''.join(random.choices(letters_and_digits, k=length))

customer = {}
customer['CUSTOMER_ID'] = generate_customer_id()
print(customer['CUSTOMER_ID'])

3836192752

In [ ]:
#GENERATE CUSTOMER CUSTOMER - MILLIONS OF RECORDS
#--------------------------
from faker import Faker
from faker.providers.phone_number import Provider
import pandas as pd
import random
import string

fake = Faker(locale='en_PH')

#create random PH phone number
class PhilippinesPhoneNumberProvider(Provider):
    def philippines_phone_number(self):
        return f'+63 {self.msisdn()[3:]}'  # msisdn generates a complete string of numbers, this formats it
fake.add_provider(PhilippinesPhoneNumberProvider)

#create random account number
def generate_customer_id(length=10):
    letters_and_digits =  string.digits
    return ''.join(random.choices(letters_and_digits, k=length))

def create_customers(data):
    #create an empty list to add our customer dictionaries
    data_list = []
    for i in range (1, data):
        customer = {}
        customer['CUSTOMER_ID'] = generate_customer_id();
        customer['FIRST_NAME'] = fake.first_name()
        customer['LAST_NAME'] = fake.last_name()
        customer['EMAILID'] = fake.email()
        customer['ADDRESS'] = fake.metro_manila_address()
        customer['GENDER'] = fake.passport_gender()
        customer['COUNTRY'] = "Philippines"
        customer['PHONENO'] = fake.philippines_phone_number()
        customer['PROFESSION'] = fake.random_element(elements=[
    'Call Center Agent', 'Customer Service Representative', 'Software Developer', 'IT Specialist', 'Nurse', 'Healthcare Professional', 'Data Analyst', 'Real Estate Agent', 'Teacher', 'Bank Manager', 'Financial Advisor', 'Virtual Assistant', 'Delivery Driver', 'Logistics Personnel', 'Marketing Manager', 'Digital Marketer', 'Accountant', 'Engineer', 'Architect', 'Pharmacist', 'Police Officer', 'Firefighter', 'Chef', 'Waiter', 'Hotel Manager', 'Electrician', 'Plumber', 'Mechanic', 'Journalist', 'Photographer', 'Graphic Designer', 'Social Worker', 'Human Resources Manager', 'Lawyer', 'Dentist', 'Psychologist', 'Tutor', 'Farmer', 'Fisherman', 'Sales Executive', 'Business Analyst', 'Entrepreneur', 'Translator', 'Interpreter', 'Event Planner', 'Researcher', 'Librarian', 'Taxi Driver', 'Pilot', 'Flight Attendant', 'Security Guard', 'Carpenter', 'Welder', 'Auditor', 'Fashion Designer', 'Veterinarian', 'Nutritionist', 'Physical Therapist', 'Occupational Therapist', 'Surgeon', 'Anesthesiologist', 'Cinematographer', 'Musician', 'Actor', 'Author', 'Poet', 'Editor', 'Broadcaster', 'Radio DJ', 'TV Presenter', 'Animator', 'Software Tester', 'QA Analyst', 'Database Administrator', 'Network Administrator', 'Cybersecurity Specialist', 'SEO Specialist', 'Content Writer', 'Blogger', 'Social Media Manager', 'Economist', 'Policy Analyst', 'Urban Planner', 'Civil Engineer', 'Mechanical Engineer', 'Electrical Engineer', 'Chemical Engineer', 'Environmental Scientist', 'Statistician', 'Mathematician', 'Philosopher', 'Archaeologist', 'Geologist', 'Astronomer', 'Meteorologist', 'Bartender', 'Historian', 'Anthropologist', 'Political Scientist', 'Therapist', 'Chief Executive Officer', 'Chief Financial Officer', 'Chief Operations Officer', 'Chief Technology Officer', 'Chief Marketing Officer', 'Chief Information Officer', 'Chief Risk Officer', 'Chief Compliance Officer', 'Chief Human Resources Officer', 'President', 'Vice President',
    'ABA Therapist', 'ABAP Developer', 'Academic Administrator', 'Academic Advisor', 'Academic Coach', 'Account Executive', 'Accounting Clerk', 'Actuary', 'Advertising Manager', 'Aerospace Engineer', 'Agricultural Engineer', 'Air Traffic Controller', 'Aircraft Mechanic', 'Animator', 'Anthropologist', 'App Developer', 'Archivist', 'Art Director', 'Artist', 'Assembler', 'Assistant Manager', 'Astronomer', 'Athletic Trainer', 'Auditor', 'Author', 'Auto Mechanic', 'Bakery Manager', 'Bank Teller', 'Bartender', 'Biochemist', 'Biomedical Engineer', 'Biostatistician', 'Blacksmith', 'Bookkeeper', 'Brand Manager', 'Budget Analyst', 'Builder', 'Business Analyst', 'Butcher', 'Camera Operator', 'Carpenter', 'Cartographer', 'Cashier', 'Chef', 'Chemist', 'Chief Executive Officer', 'Chief Financial Officer', 'Chief Marketing Officer', 'Chief Operating Officer', 'Chief Technology Officer', 'Civil Engineer', 'Claims Adjuster', 'Clean Energy Specialist', 'Clinical Psychologist', 'Clinical Research Coordinator', 'Coach', 'Coach Driver', 'Coast Guard', 'Commercial Pilot', 'Communications Specialist', 'Compliance Officer', 'Computer Programmer', 'Computer Scientist', 'Construction Manager', 'Consultant', 'Content Writer', 'Controller', 'Copywriter', 'Cost Estimator', 'Counselor', 'Courier', 'Credit Analyst', 'Customer Service Manager', 'Data Analyst', 'Data Scientist', 'Database Administrator', 'Dentist', 'Designer', 'Developer', 'Dietitian', 'Diplomat', 'Doctor', 'Dog Trainer', 'Draftsman', 'Driver', 'Economist', 'Editor', 'Electrical Engineer', 'Electrician', 'Elementary School Teacher', 'Emergency Medical Technician', 'Environmental Engineer', 'Environmental Scientist', 'Event Planner', 'Fashion Designer', 'Film Director', 'Financial Advisor', 'Financial Analyst', 'Firefighter', 'Fitness Trainer', 'Flight Attendant', 'Food Scientist', 'Forensic Scientist', 'Forester', 'Furniture Maker', 'Game Developer', 'Geologist', 'Graphic Designer', 'Hairdresser', 'Health Educator', 'Healthcare Administrator', 'Healthcare Professional', 'Historian', 'Hotel Manager', 'Human Resources Manager', 'HVAC Technician', 'Industrial Engineer', 'Information Security Analyst', 'Information Technology Manager', 'Insurance Agent', 'Instructional Designer', 'Interior Designer', 'Interpreter', 'Investment Banker', 'Investment Manager', 'Janitor', 'Journalist', 'Judge', 'Laboratory Technician', 'Landscaper', 'Librarian', 'Library Assistant', 'Life Coach', 'Linguist', 'Litigation Lawyer', 'Loan Officer', 'Logistics Coordinator', 'Machine Operator', 'Machine Learning Engineer', 'Machinist', 'Magician', 'Maintenance Technician', 'Management Consultant', 'Marine Biologist', 'Market Research Analyst', 'Marketing Coordinator', 'Marketing Manager', 'Massage Therapist', 'Mathematician', 'Mechanical Engineer', 'Mechanical Technician', 'Medical Assistant', 'Medical Laboratory Technician', 'Medical Transcriptionist', 'Mental Health Counselor', 'Meteorologist', 'Microbiologist', 'Middle School Teacher', 'Mobile App Developer', 'Mortgage Broker', 'Music Producer', 'Musician', 'Network Administrator', 'Neurologist', 'Nurse', 'Nutritionist', 'Occupational Therapist', 'Office Administrator', 'Office Assistant', 'Operations Manager', 'Optometrist', 'Pediatrician', 'Personal Trainer', 'Pharmacist', 'Photographer', 'Physical Therapist', 'Physicist', 'Pilot', 'Plumber', 'Police Officer', 'Political Scientist', 'Portfolio Manager', 'PR Specialist', 'Product Manager', 'Product Designer', 'Production Manager', 'Professor', 'Project Manager', 'Psychologist', 'Public Relations Officer', 'Quality Assurance Analyst', 'Quality Control Inspector', 'Radiologic Technologist', 'Real Estate Agent', 'Receptionist', 'Registered Nurse', 'Research Assistant', 'Research Scientist', 'Restaurant Manager', 'Retail Manager', 'Safety Officer', 'Sales Executive', 'Sales Manager', 'Sanitation Worker', 'School Counselor', 'Scientist', 'Scrum Master', 'Secondary School Teacher', 'SEO Specialist', 'Social Media Manager', 'Social Worker', 'Software Developer', 'Software Engineer', 'Soil Scientist', 'Songwriter', 'Special Education Teacher', 'Speech Therapist', 'Statistician', 'Store Manager', 'Structural Engineer', 'Substance Abuse Counselor', 'Surgeon', 'Surveyor', 'Systems Administrator', 'Tax Advisor', 'Tax Preparer', 'Teacher', 'Technical Support Specialist', 'Technical Writer', 'Telecommunications Specialist', 'Taxi Driver', 'Teacher Assistant', 'Tour Guide', 'Training Specialist', 'Translator', 'Transportation Planner', 'Travel Agent', 'Truck Driver', 'UI/UX Designer', 'Underwriter', 'Urban Planner', 'User Experience Researcher', 'Veterinarian', 'Video Editor', 'Videographer', 'Waiter', 'Warehouse Manager', 'Web Designer', 'Web Developer', 'Welder', 'Writer', 'Zoologist'
])
        customer['DOB'] = fake.date_of_birth()
        customer['MONTHLY_SALARY'] = fake.random_int (min=0, max=450000, step=1000)

        data_list.append (customer)

    return pd.DataFrame(data_list)

export = create_customers (978351000) #978,351,000 
export.to_csv("customers.csv")

,CUSTOMER_ID,FIRST_NAME,LAST_NAME,EMAILID,ADDRESS,GENDER,COUNTRY,PHONENO,PROFESSION,DOB,MONTHLY_SALARY
0,3686497481,Christina,Barton,christina90@example.net,"1443 Citrine Road, Brooks Cove, Pateros, 1725 ...",F,Philippines,+63 9472794419,Data Analyst,1983-05-22,149000
1,5477714170,William,Bush,nblackwell@example.org,"Block 07 Lot 93 Camia Estates Phase 8, Olson S...",M,Philippines,+63 0171544944,Chief Risk Officer,2005-07-05,314000
2,3996101544,Jonathan,Gray,dennis63@example.org,"Unit 1233 Mcdonald Apartments, 806 Tulip Road ...",F,Philippines,+63 1820043893,Bartender,1967-07-23,76000
3,0304460822,Michael,Hardin,phamashley@example.net,"8238 Pisces Street, Baldwin Village 8, Taguig,...",F,Philippines,+63 3235678618,Philosopher,1975-01-29,185000
4,9573115948,Tammy,Walker,miguelhughes@example.com,"B15 L69 Opal Estates 2, Matumtum Boulevard, Pa...",M,Philippines,+63 9574075395,Soil Scientist,2007-10-22,191000
...,...,...,...,...,...,...,...,...,...,...,...
194,7276293719,Brenda,Stanley,andrea70@example.net,"9604 Cucumber Drive, Kamias Subdivision Phase ...",F,Philippines,+63 5653123328,Event Planner,1980-03-21,340000
195,2142751003,Devin,White,wheelergarrett@example.net,"312 86th Road, Magnolia Homes, Valenzuela, 144...",M,Philippines,+63 6208702644,Actor,1928-02-22,172000
196,9398115437,Elizabeth,Mccall,benjamingonzales@example.net,"3720 Tabayoc Avenue, Santol Village, Marikina,...",M,Philippines,+63 2961737436,Electrician,1998-03-30,422000
197,6038589856,Eric,Pearson,ihaney@example.net,"9075 Palali Street, Knox Village Phase 9, Tagu...",M,Philippines,+63 1560683909,Interpreter,1943-05-02,47000
198,8510601867,Justin,Ritter,diane66@example.net,"5027 Turquoise Drive, Pasig, 1428 Metro Manila",F,Philippines,+63 1894791055,Auditor,1914-07-04,152000

In [ ]:
#GENERATE CREDIT CARD TRANSACTIONS - MILLIONS OF RECORDS
#--------------------------
from faker import Faker
import pandas as pd
fake = Faker(locale='en_PH')

def create_cc_transactions(data):
    #create an empty list to add our cc_transaction dictionaries
    data_list = []
    for i in range (1, data):
        cc_transaction = {}
        cc_transaction['ACCOUNT_NUMBER'] = fake.bban()
        cc_transaction['AMOUNT'] = fake.random_int (min=1000, max=150000, step=500)
        cc_transaction['CHANNEL'] = fake.random_element(elements=  ['POS', 'Online', "ATM", "Mobile App", "Branch"])
        cc_transaction['CURRENCY'] = fake.random_element(elements=  ['PHP', 'SGD', 'USD','AUD'])
        cc_transaction['MERCHANT_CATEGORY_CODE'] = fake.random_number(4)
        cc_transaction['MERCHANT_NAME'] = fake.company()
        cc_transaction['TRANSACTION_DATETIME'] = fake.date_time_this_year()
        cc_transaction['TRANSACTION_TYPE'] = fake.random_element(elements=  ['Purchase', 'Withdrawal', "Payment", "Refund"])
        data_list.append (cc_transaction)

    return pd.DataFrame(data_list)

data = create_cc_transactions(100)
data.to_csv("credit card transactions.csv")

Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.
Numbers generated by this method are purely hypothetical.